[velox]
build_args = ['-trimpath', '-ldflags', '-s -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.version=${APP_VERSION} -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.buildTime=${TIME}']

[roadrunner]
ref = "v${APP_VERSION}"

[github]
[github.token]
token = "${GH_PUBLIC_TOKEN}"

[github.plugins]
logger = { ref = "v4.1.7", owner = "roadrunner-server", repository = "logger" }
http = { ref = "v4.1.11", owner = "roadrunner-server", repository = "http" }
server = { ref = "v4.1.8", owner = "roadrunner-server", repository = "server" }
ip_resolver = { ref = "v0.1.1", owner = "loperd", repository = "ip_resolver" }

[log]
level = "debug"
mode = "production"