[velox]
build_args = ['-trimpath', '-ldflags', '-s -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.version=v2023.1.4 -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.buildTime=10:00:00']

[roadrunner]
ref = "v2023.1.4"

[github.plugins]
# ref -> master, commit or tag
logger = { ref = "master", owner = "roadrunner-server", repository = "logger" }
server = { ref = "master", owner = "roadrunner-server", repository = "server" }
http = { ref = "master", owner = "roadrunner-server", repository = "http" }
ip_resolver = { ref = "master", owner = "loperd", repository = "ip_resolver", replace = "/ip_resolver" }

[log]
level = "info"
mode = "development"